

**************
Amazon Kinesis
**************
    - Amazon Kinesis makes it easy to collect, process, and analyze real-time, streaming data so you can get timely 
      insights and react quickly to new information
    - Amazon Kinesis offers key capabilities to cost-effectively process streaming data at any scale, along with the 
      flexibility to choose the tools that best suit the requirements of your application
    - With Amazon Kinesis, you can ingest real-time data such as video, audio, application logs, website click-streams,
      and IoT telemetry data for machine learning, analytics, and other applications
    - Amazon Kinesis enables you to process and analyze data as it arrives and respond instantly instead of having 
      to wait until all your data is collected before the processing can begin
    *********
    Real-time
    *********
        - Amazon Kinesis enables you to ingest, buffer, and process streaming data in real-time, so you can 
          derive insights in seconds or minutes instead of hours or day
    *************
    Fully managed
    *************
        - Amazon Kinesis is fully managed and runs your streaming applications without requiring you to manage 
          any infrastructure
    ********
    Scalable
    ********
        - Amazon Kinesis can handle any amount of streaming data and process data from hundreds of thousands 
          of sources with very low latencies.
**************
Data streaming
**************
    - Streaming data is data that is generated continuously by thousands of data sources, which typically send 
      in the data records simultaneously, and in small sizes (order of Kilobytes)
    - Streaming data includes a wide variety of data such as log files generated by customers using your mobile 
      or web applications, ecommerce purchases, in-game player activity, information from social networks, 
      financial trading floors, or geospatial services, and telemetry from connected devices or instrumentation 
      in data centers 